"""Regenerate the JSON-LD structured data blocks from the CMS content files.

Why this exists: events, pricing and the common questions are edited in the
CMS at /admin/, but AI search engines and Google read structured data from
the page source. This script rewrites the JSON-LD in each page so the two
never drift apart.

RUN THIS whenever pricing, events or the FAQ change in a way that matters
for search:

    python tools/build-schema.py

It rewrites everything between the AUTO-SCHEMA markers in each HTML file and
touches nothing else.
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = "https://sctechia.com.au"

START = "<!-- AUTO-SCHEMA:START - generated by tools/build-schema.py, do not hand-edit -->"
END = "<!-- AUTO-SCHEMA:END -->"


def load(name):
    with open(os.path.join(ROOT, 'content', name), encoding='utf-8') as f:
        return json.load(f)


pricing = load('pricing.json')['tiers']
events = load('events.json')['events']
faqs = load('faq.json')['faqs']
board = load('board.json')['members']

ORG = {
    "@type": ["Organization", "NGO"],
    "@id": SITE + "/#org",
    "name": "Sunshine Coast Tech Alliance",
    "alternateName": ["SCTechIA", "Sunshine Coast Technology Industry Alliance"],
    "url": SITE,
    "logo": {"@type": "ImageObject", "url": SITE + "/images/logo.png"},
    "image": SITE + "/images/hero-city.jpg",
    "description": ("The peak industry body for the Sunshine Coast digital economy, connecting technology "
                    "businesses, digital leaders, innovators, educators, government and investors to drive "
                    "growth, capability and opportunity across the region."),
    "slogan": "The Gateway to the Digital Economy",
    "address": {
        "@type": "PostalAddress",
        "addressLocality": "Maroochydore",
        "addressRegion": "QLD",
        "addressCountry": "AU",
    },
    "areaServed": {
        "@type": "Place",
        "name": "Sunshine Coast, Queensland, Australia",
    },
    "contactPoint": {
        "@type": "ContactPoint",
        "contactType": "membership and general enquiries",
        "email": "info@sctechia.com.au",
        "areaServed": "AU",
        "availableLanguage": "English",
    },
    "sameAs": [
        "https://www.linkedin.com/company/sctechia/",
        "https://www.facebook.com/sctechia",
        "https://www.instagram.com/sctechia/",
    ],
    "knowsAbout": [
        "Digital infrastructure", "Artificial intelligence and automation",
        "Cyber security and digital trust", "Digital transformation",
        "Emerging technologies", "Digital media and creative technologies",
        "Technology talent and skills", "Technology enablement",
    ],
    "member": [
        {"@type": "Person", "name": m["name"], "jobTitle": m["role"],
         "worksFor": {"@type": "Organization", "name": m["company"]}}
        for m in board
    ],
}

WEBSITE = {
    "@type": "WebSite",
    "@id": SITE + "/#website",
    "url": SITE,
    "name": "Sunshine Coast Tech Alliance",
    "inLanguage": "en-AU",
    "publisher": {"@id": SITE + "/#org"},
}


def price_value(t):
    return t["priceDisplay"].replace(",", "") if t["priceMode"] == "amount" else None


def offers():
    out = []
    for t in pricing:
        offer = {
            "@type": "Offer",
            "name": t["name"] + " membership",
            "description": t["description"],
            "category": "Membership",
            "url": SITE + "/join",
            "availability": "https://schema.org/InStock",
            "seller": {"@id": SITE + "/#org"},
        }
        pv = price_value(t)
        if pv:
            offer["price"] = pv
            offer["priceCurrency"] = "AUD"
            offer["eligibleDuration"] = {"@type": "QuantitativeValue", "value": 1, "unitCode": "ANN"}
        out.append(offer)
    return out


MONTHS = {m: i for i, m in enumerate(
    ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], 1)}


def parse_date(label):
    """Pull an ISO date out of a human date label like '16 Sep 2026 - All day'.

    Returns None for labels with no real date ('Coming soon', 'Quarterly').
    Schema.org requires a startDate on an Event, so an event without a
    confirmed date is left out rather than published with a fake one.
    """
    m = re.search(r'\b(\d{1,2})\s+([A-Z][a-z]{2})[a-z]*\s+(\d{4})\b', label)
    if not m:
        return None
    day, mon, year = m.group(1), m.group(2), m.group(3)
    if mon not in MONTHS:
        return None
    return '%s-%02d-%02d' % (year, MONTHS[mon], int(day))


def event_items():
    out = []
    for e in events:
        start = parse_date(e.get("dateLabel", ""))
        if not start:
            continue
        ev = {
            "@type": "Event",
            "name": e["title"],
            "description": e["description"],
            "startDate": start,
            "eventAttendanceMode": "https://schema.org/OfflineEventAttendanceMode",
            "eventStatus": "https://schema.org/EventScheduled",
            "location": {"@type": "Place", "name": e["location"],
                         "address": {"@type": "PostalAddress", "addressRegion": "QLD", "addressCountry": "AU"}},
            "organizer": {"@id": SITE + "/#org"},
        }
        if e.get("moreInfoUrl"):
            ev["url"] = e["moreInfoUrl"]
        out.append(ev)
    return out


def faq_page(page_id):
    return {
        "@type": "FAQPage",
        "@id": page_id + "#faq",
        "mainEntity": [
            {"@type": "Question", "name": f["question"],
             "acceptedAnswer": {"@type": "Answer", "text": f["answer"]}}
            for f in faqs
        ],
    }


def breadcrumb(page_url, label):
    return {
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "Home", "item": SITE + "/"},
            {"@type": "ListItem", "position": 2, "name": label, "item": page_url},
        ],
    }


def block(graph):
    payload = {"@context": "https://schema.org", "@graph": graph}
    return (START + '\n<script type="application/ld+json">\n'
            + json.dumps(payload, indent=2, ensure_ascii=False)
            + '\n</script>\n' + END)


def write_block(filename, graph):
    path = os.path.join(ROOT, filename)
    s = open(path, encoding='utf-8').read()
    new = block(graph)
    if START in s:
        s = re.sub(re.escape(START) + r'.*?' + re.escape(END), lambda _: new, s, flags=re.S)
    else:
        # Replace the first hand-written ld+json block, or insert before </head>
        m = re.search(r'<script type="application/ld\+json">.*?</script>', s, re.S)
        if m:
            s = s[:m.start()] + new + s[m.end():]
        else:
            s = s.replace('</head>', new + '\n</head>')
    open(path, 'w', encoding='utf-8').write(s)
    print('  schema written:', filename)


write_block('index.html', [
    ORG, WEBSITE,
    {"@type": "WebPage", "@id": SITE + "/#webpage", "url": SITE + "/",
     "name": "Sunshine Coast Tech Alliance | The Gateway to the Digital Economy",
     "isPartOf": {"@id": SITE + "/#website"}, "about": {"@id": SITE + "/#org"},
     "inLanguage": "en-AU"},
] + event_items())

write_block('join.html', [
    ORG, WEBSITE,
    {"@type": "WebPage", "@id": SITE + "/join#webpage", "url": SITE + "/join",
     "name": "Become a Member | Sunshine Coast Tech Alliance",
     "isPartOf": {"@id": SITE + "/#website"}, "inLanguage": "en-AU"},
    breadcrumb(SITE + "/join", "Become a Member"),
    faq_page(SITE + "/join"),
    {"@type": "Service", "@id": SITE + "/join#membership",
     "name": "Sunshine Coast Tech Alliance membership",
     "serviceType": "Industry association membership",
     "provider": {"@id": SITE + "/#org"},
     "areaServed": {"@type": "Place", "name": "Sunshine Coast, Queensland, Australia"},
     "offers": offers()},
])

for fn, label, slug in [('privacy.html', 'Privacy Policy', '/privacy'),
                        ('terms.html', 'Terms of Use', '/terms')]:
    write_block(fn, [
        ORG,
        {"@type": "WebPage", "@id": SITE + slug + "#webpage", "url": SITE + slug,
         "name": label + " | Sunshine Coast Tech Alliance",
         "isPartOf": {"@id": SITE + "/#website"}, "inLanguage": "en-AU"},
        breadcrumb(SITE + slug, label),
    ])

print('done')
